spring:
  application:
    name: ag-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fdchenhui/fdchenhui.git
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka
server:
  port: 8750
